version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
  db:
    build:
      context: ./db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  db-data: